MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0230
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 5, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
    K_GROUP: 4
  
    DIRECTIONS: [
      ['hilbert_a', 'hilbert_b', 'hilbert_c' , 'hilbert_d'],
      ['hilbert_a_shift', 'hilbert_b_flip', 'hilbert_c', 'hilbert_d'],

      ['hilbert_a', 'hilbert_b', 'hilbert_c' , 'hilbert_d'],
      ['hilbert_a', 'hilbert_b', 'hilbert_c' , 'hilbert_d'],

      ['hilbert_a', 'hilbert_b', 'hilbert_c' , 'hilbert_d'],
      ['hilbert_a', 'hilbert_b', 'hilbert_c' , 'hilbert_d'],
      ['hilbert_a', 'hilbert_b', 'hilbert_c' , 'hilbert_d'],
      ['hcurve_a', 'hcurve_a', 'hcurve_a_flip', 'hcurve_a_shift'],
      ['hilbert_a_shift', 'hilbert_b_flip', 'hilbert_c_shift_flip', 'hilbert_d'],

      ['hilbert_a', 'hilbert_b', 'hilbert_c', 'hilbert_d'],
      ['hcurve_a', 'hcurve_b', 'hilbert_c_shift_flip', 'hilbert_d'],
    ]
    DIRECTION_AWARE: True
    SC_ATTN: False

DATA:
  IMG_SIZE: 128


