MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0230
  DROP_PATH_RATE: 0.3
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 5, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
    K_GROUP: 4
    
    DIRECTIONS: [
      ['hilbert_a', 'hilbert_a_flip', 'hcurve_a' , 'hcurve_a_flip'],
      ['h', 'v', 'h_flip' , 'v_flip'],

      ['hilbert_a', 'hilbert_a_flip', 'hcurve_b' , 'hcurve_b_flip'],
      ['h', 'v', 'h_flip' , 'v_flip'],

      ['hilbert_a', 'hilbert_a_flip', 'hcurve_b' , 'hcurve_b_flip'],
      ['h', 'v', 'h_flip' , 'v_flip'],
      ['hilbert_a', 'hilbert_a_flip', 'hcurve_b' , 'hcurve_b_flip'],
      ['h', 'v', 'h_flip' , 'v_flip'],
      ['hilbert_a', 'hilbert_a_flip', 'hcurve_b' , 'hcurve_b_flip'],
      
      ['h', 'v', 'h_flip' , 'v_flip'],
      ['hilbert_a', 'hilbert_a_flip', 'hcurve_b' , 'hcurve_b_flip'],    
    ]
    DIRECTION_AWARE: False
    SC_ATTN: False
    POSEMBED: True
    

DATA:
  IMG_SIZE: 128


